general.import = [
"/home/blvck/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
general.live_config_reload = true
window.opacity = 1.0
window.decorations = "None"
window.decorations_theme_variant = "Dark"
[terminal]
shell = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[font]
size = 9

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold Italic"
#ComicShannsMono Nerd Font Mono

[scrolling]
history = 5000

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window.padding]
x = 1
y = 1

[bell]
animation = "EaseOut"
duration = 1
color = "#013220"

[selection]
save_to_clipboard = true

[cursor]
#blinking = "On"

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]
